### ISSUE TITLE
Error when starting Strapi after installing the plugin 

### ISSUE THREAD

**Issue by adrienzagar** [Freyb/strapi-plugin-copy-component#1]
Strapi version : `"@strapi/strapi": "^4.2.0",`

Hi,

I am facing an error when starting Strapi. 
What i did : 

1. `npm install strapi-plugin-copy-component --save`
2. `npm run build` to build Strapi
3. `npm run start`

The error is the next one : 

```
> pro-backoffice@0.1.0 start
> strapi start

[2023-07-10 11:18:01.513] debug: ⛔️ Server wasn't able to start properly.
[2023-07-10 11:18:01.514] error: Cannot read properties of undefined (reading 'registerOverride')
TypeError: Cannot read properties of undefined (reading 'registerOverride')
    at Object.module.exports [as register] (/home/azagar/dev/project/biogaran/biogaran-pro-backoffice/node_modules/@strapi/strapi/node_modules/@strapi/plugin-upload/server/register.js:28:7)
    at async Object.register (/home/azagar/dev/project/biogaran/biogaran-pro-backoffice/node_modules/@strapi/strapi/lib/core/domain/module/index.js:47:7)
    at async Object.register (/home/azagar/dev/project/biogaran/biogaran-pro-backoffice/node_modules/@strapi/strapi/lib/core/registries/modules.js:33:9)
    at async Strapi.runLifecyclesFunctions (/home/azagar/dev/project/biogaran/biogaran-pro-backoffice/node_modules/@strapi/strapi/lib/Strapi.js:545:5)
    at async Strapi.register (/home/azagar/dev/project/biogaran/biogaran-pro-backoffice/node_modules/@strapi/strapi/lib/Strapi.js:406:5)
    at async Strapi.load (/home/azagar/dev/project/biogaran/biogaran-pro-backoffice/node_modules/@strapi/strapi/lib/Strapi.js:491:5)
    at async Strapi.start (/home/azagar/dev/project/biogaran/biogaran-pro-backoffice/node_modules/@strapi/strapi/lib/Strapi.js:218:9)

```

A value seems to be undefined.

Any idea to solve the problem ?

**Comment by adrienzagar** [comment]
I tried to upgrade my Strapi version to 4..9.0 in my package.json : 
```
    "@strapi/plugin-documentation": "^4.9.0",
    "@strapi/plugin-i18n": "^4.9.0",
    "@strapi/plugin-users-permissions": "^4.9.0",
    "@strapi/strapi": "4.9.0",
```
I reach to start the local envrionnement but i am facing a blank admin panel page and a new error is showing up in the console : 
![image](https://github.com/Freyb/strapi-plugin-copy-component/assets/59897360/42cfe583-3509-4561-b3e1-b3b74d46ef80)
